bash space formating

diff --git a/freenx-redesign/server/compatibility/nxserver-login b/freenx-redesign/server/compatibility/nxserver-login
--- a/freenx-redesign/server/compatibility/nxserver-login
+++ b/freenx-redesign/server/compatibility/nxserver-login
@@ -75,21 +75,24 @@ _NXLOADCONFIG="$(cd $(dirname $0) && pwd -L)/nxloadconfig"
 [ -f "$_NXLOADCONFIG" ] || _NXLOADCONFIG='nxloadconfig'
 
 #Read the nxserver-login.cfg file and load some helper functions
-. "$_NXLOADCONFIG" --config="nxserver-login" || { echo "NX 503> Internal server error. nxloadconfig could not be loaded."; exit 1; }
+. "$_NXLOADCONFIG" --config="nxserver-login" || {
+	echo "NX 503> Internal server error. nxloadconfig could not be loaded."
+	exit 1
+}
 
-echo_x() 
-{
+echo_x() {
 	echo "$@"
-  nxlog_log DEBUG "Sent: $@"
+	nxlog_log DEBUG "Sent: $@"
 }
 
-read_x()
-{
-	read -t "${READ_X_TIMEOUT:-10}" "$@" || { echo_x; return 1; }
+read_x() {
+	read -t "${READ_X_TIMEOUT:-10}" "$@" || {
+		echo_x
+		return 1
+	}
 }
 
-read_x_prompt() 
-{
+read_x_prompt() {
 	echo_x -n "$1"
 	shift
 	read_x "$@"
@@ -97,147 +100,138 @@ read_x_prompt()
 
 # helper functions
 
-timeout()
-{
+timeout() {
 	echo_x $"NX> 996 ERROR: Operation timeout in server protocol"
 	echo_x $"NX> 999 Bye."
 	exit 1
 }
 
-config_check()
-{
-  # Re-check configuration keys
+config_check() {
+	# Re-check configuration keys
 
-  if [ -n "$NXSERVER_LOGIN_HOOK_LOGIN_USER" -a ! -x "$NXSERVER_LOGIN_HOOK_LOGIN_USER" ]
-  then
-    nxlog_log WARNING $"Warning: Configuration key NXSERVER_LOGIN_HOOK_LOGIN_USER=$NXSERVER_LOGIN_HOOK_LOGIN_USER is invalid. Reset to \"\"."
-    NXSERVER_LOGIN_HOOK_LOGIN_USER=""
-  fi
+	if [ -n "$NXSERVER_LOGIN_HOOK_LOGIN_USER" -a ! -x "$NXSERVER_LOGIN_HOOK_LOGIN_USER" ]; then
+		nxlog_log WARNING $"Warning: Configuration key NXSERVER_LOGIN_HOOK_LOGIN_USER=$NXSERVER_LOGIN_HOOK_LOGIN_USER is invalid. Reset to \"\"."
+		NXSERVER_LOGIN_HOOK_LOGIN_USER=""
+	fi
 
-  case "$NXSERVER_LOGIN_AUTHENTICATION_METHOD" in
-    ssh|su)
-    ;;
-    *)
-      nxlog_log WARNING $"Warning: Configuration key NXSERVER_LOGIN_AUTHENTICATION_METHOD=$NXSERVER_LOGIN_AUTHENTICATION_METHOD is invalid. Reset to su."
-      NXSERVER_LOGIN_AUTHENTICATION_METHOD="su"
-    ;;
-  esac
+	case "$NXSERVER_LOGIN_AUTHENTICATION_METHOD" in
+		ssh | su) ;;
+		*)
+			nxlog_log WARNING $"Warning: Configuration key NXSERVER_LOGIN_AUTHENTICATION_METHOD=$NXSERVER_LOGIN_AUTHENTICATION_METHOD is invalid. Reset to su."
+			NXSERVER_LOGIN_AUTHENTICATION_METHOD="su"
+			;;
+	esac
 }
 
-nxserver-login_main()
-{
-  # main program
+nxserver-login_main() {
+	# main program
 
-  echo_x "HELLO NXSERVER - Version $NX_VERSION $NX_LICENSE"
-  nxlog_log INFO "Started"
+	echo_x "HELLO NXSERVER - Version $NX_VERSION $NX_LICENSE"
+	nxlog_log INFO "Started"
 
-  # Login stage
-  while read_x_prompt "NX> 105 " CMD
-  do
-    nxlog_log DEBUG "Got: $CMD"
-    CMD=$(echo $CMD | tr '[A-Z]' '[a-z]')
-    case "$CMD" in
-      quit)
-        echo_x "Quit"
-        nxlog_log DEBUG "Exiting"
-        break
-      ;;
-      exit)
-        echo_x "Exit"
-        nxlog_log DEBUG "Exiting"
-        break
-      ;;
-      bye)
-        echo_x "Bye"
-        nxlog_log DEBUG "Exiting"
-        break
-      ;;
-      hello*)
-        echo_x "$CMD"
-        CLIENT_PROTO="$(echo $CMD | sed 's/.*[Vv]ersion \(.*\)/\1/g')"
-        PROTO="$(echo -e "$NX_VERSION\n$CLIENT_PROTO" | \
-            sort -n -t. -k1,1 -k2,2 -k3 | head -1)"
-        echo_x $"NX> 134 Accepted protocol: $PROTO"
-      ;;
-      set\ auth_mode\ *)
-        mode=$(echo "$CMD" | sed 's/^[^[:blank:]]\+ [^[:blank:]]\+ \(.*\)/\1/')
-        echo_x "Set auth_mode: $mode"
-        if ! echo "$mode" | egrep -q "password"; then
-          echo_x "NX> 500 ERROR: unknown auth mode ''"
-        fi
-      ;;
-      set\ shell_mode\ *)
-        mode=$(echo "$CMD" | sed 's/^[^[:blank:]]\+ [^[:blank:]]\+ \(.*\)/\1/')
-        echo_x "Set shell_mode: $mode"
-        if ! echo "$mode" | egrep -q "shell"; then
-          echo_x "NX> 500 ERROR: unknown shell mode ''"
-        fi
-      ;;
-      login)
-        echo_x "$CMD"
-        LOGIN_SUCCESS="0"
+	# Login stage
+	while read_x_prompt "NX> 105 " CMD; do
+		nxlog_log DEBUG "Got: $CMD"
+		CMD=$(echo $CMD | tr '[A-Z]' '[a-z]')
+		case "$CMD" in
+			quit)
+				echo_x "Quit"
+				nxlog_log DEBUG "Exiting"
+				break
+				;;
+			exit)
+				echo_x "Exit"
+				nxlog_log DEBUG "Exiting"
+				break
+				;;
+			bye)
+				echo_x "Bye"
+				nxlog_log DEBUG "Exiting"
+				break
+				;;
+			hello*)
+				echo_x "$CMD"
+				CLIENT_PROTO="$(echo $CMD | sed 's/.*[Vv]ersion \(.*\)/\1/g')"
+				PROTO="$(echo -e "$NX_VERSION\n$CLIENT_PROTO" \
+					| sort -n -t. -k1,1 -k2,2 -k3 | head -1)"
+				echo_x $"NX> 134 Accepted protocol: $PROTO"
+				;;
+			set\ auth_mode\ *)
+				mode=$(echo "$CMD" | sed 's/^[^[:blank:]]\+ [^[:blank:]]\+ \(.*\)/\1/')
+				echo_x "Set auth_mode: $mode"
+				if ! echo "$mode" | egrep -q "password"; then
+					echo_x "NX> 500 ERROR: unknown auth mode ''"
+				fi
+				;;
+			set\ shell_mode\ *)
+				mode=$(echo "$CMD" | sed 's/^[^[:blank:]]\+ [^[:blank:]]\+ \(.*\)/\1/')
+				echo_x "Set shell_mode: $mode"
+				if ! echo "$mode" | egrep -q "shell"; then
+					echo_x "NX> 500 ERROR: unknown shell mode ''"
+				fi
+				;;
+			login)
+				echo_x "$CMD"
+				LOGIN_SUCCESS="0"
 
-        echo_x -n $"NX> 101 User: "
-        read_x USER || timeout
-        echo_x $USER
+				echo_x -n $"NX> 101 User: "
+				read_x USER || timeout
+				echo_x $USER
 
-        echo_x -n $"NX> 102 Password: "
-        read_x -s PASS || timeout
-        echo_x "**********"
-        nxlog_log INFO "Info: Using authentication method $NXSERVER_LOGIN_AUTHENTICATION_METHOD for user $USER."
+				echo_x -n $"NX> 102 Password: "
+				read_x -s PASS || timeout
+				echo_x "**********"
+				nxlog_log INFO "Info: Using authentication method $NXSERVER_LOGIN_AUTHENTICATION_METHOD for user $USER."
 
-        NODE_HOOK_LOGIN="$PATH_BIN/nxserver-login-hook"
-        [ -n "$NXSERVER_LOGIN_HOOK_LOGIN_USER" ] && \
-            NODE_HOOK_LOGIN="$NXSERVER_LOGIN_HOOK_LOGIN_USER"
-        export NODE_HOOK_LOGIN
+				NODE_HOOK_LOGIN="$PATH_BIN/nxserver-login-hook"
+				[ -n "$NXSERVER_LOGIN_HOOK_LOGIN_USER" ] \
+					&& NODE_HOOK_LOGIN="$NXSERVER_LOGIN_HOOK_LOGIN_USER"
+				export NODE_HOOK_LOGIN
 
-        # Redirection is used to get around | only being useful for stdout.
-        nxlog_log INFO "Info: Invoking nxserver-login-helper"
-        # This fifo is opened by nxserver-login-helper to log through
-        export SERVER_LOGIN_HELPER_LOG="$(mktemp -d /tmp/nxserver-login.XXXXXX)/fifo"
-        mkfifo "$SERVER_LOGIN_HELPER_LOG"
-        (
-          nxlog_log DEBUG "Starting to log nxserver-login-helper debug output $SERVER_LOGIN_HELPER_LOG"
-          NXLOG_LOG_PIPE_PREFIX="helper output:" nxlog_log_pipe DEBUG < "$SERVER_LOGIN_HELPER_LOG"
-          nxlog_log DEBUG "Finished logging nxserver-login-helper debug output"
-          # Cleanup after the fifo
-          rm "$SERVER_LOGIN_HELPER_LOG"
-          rmdir $(dirname "$SERVER_LOGIN_HELPER_LOG")
-        ) &
-        NODE_PASSWORD="$PASS" "$PATH_BIN/nxserver-login-helper" -- \
-          "$NXSERVER_LOGIN_AUTHENTICATION_METHOD" "$USER" \
-          "$PATH_BIN/nxserver-suid" "--proto=${PROTO:-}"
+				# Redirection is used to get around | only being useful for stdout.
+				nxlog_log INFO "Info: Invoking nxserver-login-helper"
+				# This fifo is opened by nxserver-login-helper to log through
+				export SERVER_LOGIN_HELPER_LOG="$(mktemp -d /tmp/nxserver-login.XXXXXX)/fifo"
+				mkfifo "$SERVER_LOGIN_HELPER_LOG"
+				(
+					nxlog_log DEBUG "Starting to log nxserver-login-helper debug output $SERVER_LOGIN_HELPER_LOG"
+					NXLOG_LOG_PIPE_PREFIX="helper output:" nxlog_log_pipe DEBUG <"$SERVER_LOGIN_HELPER_LOG"
+					nxlog_log DEBUG "Finished logging nxserver-login-helper debug output"
+					# Cleanup after the fifo
+					rm "$SERVER_LOGIN_HELPER_LOG"
+					rmdir $(dirname "$SERVER_LOGIN_HELPER_LOG")
+				) &
+				NODE_PASSWORD="$PASS" "$PATH_BIN/nxserver-login-helper" -- \
+					"$NXSERVER_LOGIN_AUTHENTICATION_METHOD" "$USER" \
+					"$PATH_BIN/nxserver-suid" "--proto=${PROTO:-}"
 
-        AUTHENTICATION_FAILED="$?"
+				AUTHENTICATION_FAILED="$?"
 
-        if [ "$AUTHENTICATION_FAILED" = "0" ]
-        then
-          true
-        elif [ "$AUTHENTICATION_FAILED" = "1" ]
-        then
-          echo_x $"NX> 404 ERROR: wrong password or login."
-          echo_x $"NX> 999 Bye."
-          exit 1
-        elif [ "$AUTHENTICATION_FAILED" = "2" ]
-        then
-          echo_x $"NX> 503 ERROR: Redirection to nxagent failed."
-          echo_x $"NX> 999 Bye."
-          exit 2
-        else
-          echo_x $"NX> 500 ERROR: Unknown error \"$AUTHENTICATION_FAILED\" occurred while logging in."
-          echo_x $"NX> 999 Bye."
-          exit 3
-        fi
+				if [ "$AUTHENTICATION_FAILED" = "0" ]; then
+					true
+				elif [ "$AUTHENTICATION_FAILED" = "1" ]; then
+					echo_x $"NX> 404 ERROR: wrong password or login."
+					echo_x $"NX> 999 Bye."
+					exit 1
+				elif [ "$AUTHENTICATION_FAILED" = "2" ]; then
+					echo_x $"NX> 503 ERROR: Redirection to nxagent failed."
+					echo_x $"NX> 999 Bye."
+					exit 2
+				else
+					echo_x $"NX> 500 ERROR: Unknown error \"$AUTHENTICATION_FAILED\" occurred while logging in."
+					echo_x $"NX> 999 Bye."
+					exit 3
+				fi
 
-        exit 0
-      ;;
-    esac
-  done
-  echo_x "NX> 999 Bye."
-  exit 0
+				exit 0
+				;;
+		esac
+	done
+	echo_x "NX> 999 Bye."
+	exit 0
 }
 
 if [ -z "${UNITTESTING:-}" ]; then
-  config_check
-  nxserver-login_main
+	config_check
+	nxserver-login_main
 fi
diff --git a/freenx-redesign/server/compatibility/nxstart b/freenx-redesign/server/compatibility/nxstart
--- a/freenx-redesign/server/compatibility/nxstart
+++ b/freenx-redesign/server/compatibility/nxstart
@@ -41,7 +41,10 @@
 # SVN: $Id: $
 #
 
-. nxloadconfig --config="nxstart" || { echo "NX 503> Internal server error. nxloadconfig could not be loaded by nxstart."; exit 1; }
+. nxloadconfig --config="nxstart" || {
+	echo "NX 503> Internal server error. nxloadconfig could not be loaded by nxstart."
+	exit 1
+}
 
 AGENT_PID="$1"
 shift
@@ -54,8 +57,8 @@ echo "Xft.dpi: 96" | LANG=C xrdb -merge 2>&1 | nxlog_log_pipe DEBUG
 
 msg="Cmd exited, nxagent (pid $AGENT_PID)"
 if kill -0 "$AGENT_PID" &>/dev/null; then
-  nxlog_log DEBUG "$msg still exists, killing"
-  kill "$AGENT_PID" || nxlog_log ERR "Killing nxagent returned error $?"
+	nxlog_log DEBUG "$msg still exists, killing"
+	kill "$AGENT_PID" || nxlog_log ERR "Killing nxagent returned error $?"
 else
-  nxlog_log NOTICE "$msg already exited"
+	nxlog_log NOTICE "$msg already exited"
 fi
diff --git a/freenx-redesign/server/test/testNxserver-login b/freenx-redesign/server/test/testNxserver-login
--- a/freenx-redesign/server/test/testNxserver-login
+++ b/freenx-redesign/server/test/testNxserver-login
@@ -18,194 +18,180 @@
 #
 # Author: diamond@google.com (Stephen Shirley)
 
-oneTimeSetUp()
-{
-  # This unit test may need to be run while installed.
-  . "./include/test-functions.inc" && setupLoadConfig
-  echo "NX_VERSION=3.0.0" >> "$PATH_ETC/general.conf"
-  NX_PROMPT="NX> 105 "
-  NX_SERVER_BANNER_REGX='^HELLO NXSERVER - Version [^[:blank:]]+ .*$'
-  LOGIN_ERROR_REPLY="NX> 404 ERROR: WRONG PASSWORD OR LOGIN."
+oneTimeSetUp() {
+	# This unit test may need to be run while installed.
+	. "./include/test-functions.inc" && setupLoadConfig
+	echo "NX_VERSION=3.0.0" >>"$PATH_ETC/general.conf"
+	NX_PROMPT="NX> 105 "
+	NX_SERVER_BANNER_REGX='^HELLO NXSERVER - Version [^[:blank:]]+ .*$'
+	LOGIN_ERROR_REPLY="NX> 404 ERROR: WRONG PASSWORD OR LOGIN."
 }
 
-setUp()
-{
-  cd "$TEST_DIR"
+setUp() {
+	cd "$TEST_DIR"
 }
 
-runPrep()
-{
-  cmd="$1"
-  shift
-  rm -f .extern.*
-  mkfifo .extern.stdin
-  mkfifo .extern.stdout
-  "$cmd" "$@" < .extern.stdin &> .extern.stdout &
-  eval "exec $EXTERN_STDIN>.extern.stdin"
-  eval "exec $EXTERN_STDOUT<.extern.stdout"
+runPrep() {
+	cmd="$1"
+	shift
+	rm -f .extern.*
+	mkfifo .extern.stdin
+	mkfifo .extern.stdout
+	"$cmd" "$@" <.extern.stdin &>.extern.stdout &
+	eval "exec $EXTERN_STDIN>.extern.stdin"
+	eval "exec $EXTERN_STDOUT<.extern.stdout"
 }
 
-runCleanup()
-{
-  eval "exec $EXTERN_STDIN>&-"
-  eval "exec $EXTERN_STDOUT<&-"
-  rm -f .extern.*
+runCleanup() {
+	eval "exec $EXTERN_STDIN>&-"
+	eval "exec $EXTERN_STDOUT<&-"
+	rm -f .extern.*
 }
 
 # Tests that check output of running nxserver script need to be in this section
-testBanner()
-{
-  runPrep nxserver-login
-  recvCheckRegx 'Banner' "$NX_SERVER_BANNER_REGX"
-  eval "exec $EXTERN_STDIN>&-"
-  recvCheck 'Prompt' "$NX_PROMPT"
-  recvCheck 'Bye' 'NX> 999 Bye.'
-  runCleanup
+testBanner() {
+	runPrep nxserver-login
+	recvCheckRegx 'Banner' "$NX_SERVER_BANNER_REGX"
+	eval "exec $EXTERN_STDIN>&-"
+	recvCheck 'Prompt' "$NX_PROMPT"
+	recvCheck 'Bye' 'NX> 999 Bye.'
+	runCleanup
 }
 
 # Tests that check output of running nxserver need to be BEFORE this line
 
-testSourceNxserver()
-{
-  UNITTESTING="1"
-  . bin/nxserver-login
-  nxloadconfig_main
+testSourceNxserver() {
+	UNITTESTING="1"
+	. bin/nxserver-login
+	nxloadconfig_main
 
-  assertEquals "Sourcing nxserver" "0" "$?"
+	assertEquals "Sourcing nxserver" "0" "$?"
 }
 
-testConfig_check()
-{
-  NXSERVER_LOGIN_HOOK_LOGIN_USER="/etc/fstab"
-  config_check
-  assertNull "config_check doesn't nuke invalid \
+testConfig_check() {
+	NXSERVER_LOGIN_HOOK_LOGIN_USER="/etc/fstab"
+	config_check
+	assertNull "config_check doesn't nuke invalid \
     \$NXSERVER_LOGIN_HOOK_LOGIN_USER value" "$NXSERVER_LOGIN_HOOK_LOGIN_USER"
 
-  NXSERVER_LOGIN_HOOK_LOGIN_USER="doesn'texist"
-  config_check
-  assertEquals "config_check doesn't change invalid \
+	NXSERVER_LOGIN_HOOK_LOGIN_USER="doesn'texist"
+	config_check
+	assertEquals "config_check doesn't change invalid \
     \$NXSERVER_LOGIN_AUTHENTICATION_METHOD to 'su'" "su" \
-    "$NXSERVER_LOGIN_AUTHENTICATION_METHOD"
+		"$NXSERVER_LOGIN_AUTHENTICATION_METHOD"
 }
 
-mainTestSetup()
-{
-  runPrep nxserver-login_main
-  recvCheckRegx 'Banner' "$NX_SERVER_BANNER_REGX"
+mainTestSetup() {
+	runPrep nxserver-login_main
+	recvCheckRegx 'Banner' "$NX_SERVER_BANNER_REGX"
 }
 
-mainTestTearDown()
-{
-  runCleanup
+mainTestTearDown() {
+	runCleanup
 }
 
-testNxserverlogin_main()
-{
-  mainTestSetup
-  eval "exec $EXTERN_STDIN>&-"
-  recvCheck 'Immediate-quit prompt' "$NX_PROMPT"
-  recvCheck 'Immediate-quit bye' 'NX> 999 Bye.'
+testNxserverlogin_main() {
+	mainTestSetup
+	eval "exec $EXTERN_STDIN>&-"
+	recvCheck 'Immediate-quit prompt' "$NX_PROMPT"
+	recvCheck 'Immediate-quit bye' 'NX> 999 Bye.'
 
-  for i in quit exit bye; do
-    mainTestSetup
-    sendRecvCheck "$i" "$i came back wrong" "${NX_PROMPT}$i"
-    recvCheck "$i bye" 'NX> 999 Bye.'
-    mainTestTearDown
-  done
+	for i in quit exit bye; do
+		mainTestSetup
+		sendRecvCheck "$i" "$i came back wrong" "${NX_PROMPT}$i"
+		recvCheck "$i bye" 'NX> 999 Bye.'
+		mainTestTearDown
+	done
 }
 
-testConfigCommands()
-{
-  local VER TYPE
+testConfigCommands() {
+	local VER TYPE
 
-  mainTestSetup
-    VER="testing testing"
-    SEND="hello nxclient - version $VER"
-    sendRecvCheck "$SEND" "Hello came back wrong" "${NX_PROMPT}$SEND"
-    recvCheck "Client hello reply wrong" "NX> 134 Accepted protocol: $VER"
+	mainTestSetup
+	VER="testing testing"
+	SEND="hello nxclient - version $VER"
+	sendRecvCheck "$SEND" "Hello came back wrong" "${NX_PROMPT}$SEND"
+	recvCheck "Client hello reply wrong" "NX> 134 Accepted protocol: $VER"
 
-    TYPE="password"
-    SEND="set auth_mode $TYPE"
-    sendRecvCheck "$SEND" "Valid auth mode came back wrong" \
-      "${NX_PROMPT}set auth_mode: $TYPE"
-    TYPE="somethingelse"
-    SEND="set auth_mode $TYPE"
-    sendRecvCheck "$SEND" "Invalid auth mode came back wrong" \
-      "${NX_PROMPT}set auth_mode: $TYPE"
-    recvCheck "Invalid auth mode accepted" "NX> 500 ERROR: unknown auth mode ''"
-  mainTestTearDown
+	TYPE="password"
+	SEND="set auth_mode $TYPE"
+	sendRecvCheck "$SEND" "Valid auth mode came back wrong" \
+		"${NX_PROMPT}set auth_mode: $TYPE"
+	TYPE="somethingelse"
+	SEND="set auth_mode $TYPE"
+	sendRecvCheck "$SEND" "Invalid auth mode came back wrong" \
+		"${NX_PROMPT}set auth_mode: $TYPE"
+	recvCheck "Invalid auth mode accepted" "NX> 500 ERROR: unknown auth mode ''"
+	mainTestTearDown
 }
 
-testLoginWrongUsername()
-{
-  local DESC NXUSERNAME NXPASSWORD
+testLoginWrongUsername() {
+	local DESC NXUSERNAME NXPASSWORD
 
-  mainTestSetup
-    sendRecvCheck "login" "Login came back wrong" "${NX_PROMPT}login"
-    DESC="Wrong username"
-    NXUSERNAME="nxfail"
-    NXPASSWORD="haha.no."
-    sendRecvCheck "$NXUSERNAME" "$DESC - username came back wrong" \
-      "NX> 101 user: $NXUSERNAME"
-    sendRecvCheckRegx "$NXPASSWORD" "$DESC - password came back wrong" \
-      '^NX> 102 password: \**$'
-    recvCheck "$DESC - login succeded when it shouldn't" "$LOGIN_ERROR_REPLY"
-    recvCheck "$DESC bye" 'NX> 999 Bye.'
-  mainTestTearDown
+	mainTestSetup
+	sendRecvCheck "login" "Login came back wrong" "${NX_PROMPT}login"
+	DESC="Wrong username"
+	NXUSERNAME="nxfail"
+	NXPASSWORD="haha.no."
+	sendRecvCheck "$NXUSERNAME" "$DESC - username came back wrong" \
+		"NX> 101 user: $NXUSERNAME"
+	sendRecvCheckRegx "$NXPASSWORD" "$DESC - password came back wrong" \
+		'^NX> 102 password: \**$'
+	recvCheck "$DESC - login succeded when it shouldn't" "$LOGIN_ERROR_REPLY"
+	recvCheck "$DESC bye" 'NX> 999 Bye.'
+	mainTestTearDown
 }
 
-testLoginRightUsernameWrongPassword()
-{
-  local DESC NXUSERNAME NXPASSWORD
+testLoginRightUsernameWrongPassword() {
+	local DESC NXUSERNAME NXPASSWORD
 
-  mainTestSetup
-    sendRecvCheck "login" "Login came back wrong" "${NX_PROMPT}login"
-    DESC="Correct username, wrong password"
-    NXUSERNAME="nxtest"
-    NXPASSWORD="haha.no."
-    sendRecvCheck "$NXUSERNAME" "$DESC - username came back wrong" \
-      "NX> 101 user: $NXUSERNAME"
-    sendRecvCheckRegx "$NXPASSWORD" "$DESC - password came back wrong" \
-      '^NX> 102 password: \**$'
-    recvCheck "$DESC - login succeded when it shouldn't" "$LOGIN_ERROR_REPLY"
-    recvCheck "$DESC bye" 'NX> 999 Bye.'
-  mainTestTearDown
+	mainTestSetup
+	sendRecvCheck "login" "Login came back wrong" "${NX_PROMPT}login"
+	DESC="Correct username, wrong password"
+	NXUSERNAME="nxtest"
+	NXPASSWORD="haha.no."
+	sendRecvCheck "$NXUSERNAME" "$DESC - username came back wrong" \
+		"NX> 101 user: $NXUSERNAME"
+	sendRecvCheckRegx "$NXPASSWORD" "$DESC - password came back wrong" \
+		'^NX> 102 password: \**$'
+	recvCheck "$DESC - login succeded when it shouldn't" "$LOGIN_ERROR_REPLY"
+	recvCheck "$DESC bye" 'NX> 999 Bye.'
+	mainTestTearDown
 }
 
-testLoginRightUsernameRightPassword()
-{
-  local DESC NXUSERNAME NXPASSWORD
+testLoginRightUsernameRightPassword() {
+	local DESC NXUSERNAME NXPASSWORD
 
-  mainTestSetup
-    sendRecvCheck "login" "Login came back wrong" "${NX_PROMPT}login"
-    DESC="Correct username, correct password"
-    NXUSERNAME="nxtest"
-    NXPASSWORD="haha.yes."
-    sendRecvCheck "$NXUSERNAME" "$DESC - username came back wrong" \
-      "NX> 101 user: $NXUSERNAME"
-    sendRecvCheckRegx "$NXPASSWORD" "$DESC - password came back wrong" \
-      "NX> 102 password: \**"
-    recvCheck "$DESC - missing mysterious blank line" " " #FIXME - dunno where this comes from
-    recvCheck "$DESC - login failed when it shouldn't" \
-      "NX> 103 WELCOME TO: $HOSTNAME USER: $NXUSERNAME"
+	mainTestSetup
+	sendRecvCheck "login" "Login came back wrong" "${NX_PROMPT}login"
+	DESC="Correct username, correct password"
+	NXUSERNAME="nxtest"
+	NXPASSWORD="haha.yes."
+	sendRecvCheck "$NXUSERNAME" "$DESC - username came back wrong" \
+		"NX> 101 user: $NXUSERNAME"
+	sendRecvCheckRegx "$NXPASSWORD" "$DESC - password came back wrong" \
+		"NX> 102 password: \**"
+	recvCheck "$DESC - missing mysterious blank line" " " #FIXME - dunno where this comes from
+	recvCheck "$DESC - login failed when it shouldn't" \
+		"NX> 103 WELCOME TO: $HOSTNAME USER: $NXUSERNAME"
 
-  mainTestTearDown
+	mainTestTearDown
 }
 
 testTimeout() {
-  local before after delay
-  READ_X_TIMEOUT=4
-  before=$(date +%s)
-  mainTestSetup
+	local before after delay
+	READ_X_TIMEOUT=4
+	before=$(date +%s)
+	mainTestSetup
 
-    recvCheck 'Immediate-quit prompt' "$NX_PROMPT"
-    recvCheck 'Immediate-quit bye' 'NX> 999 Bye.'
-    after=$(date +%s)
-    delay=$((after - before))
-    assertTrue 'Immediate-quit timeout' '[ $delay -ge $READ_X_TIMEOUT ]'
+	recvCheck 'Immediate-quit prompt' "$NX_PROMPT"
+	recvCheck 'Immediate-quit bye' 'NX> 999 Bye.'
+	after=$(date +%s)
+	delay=$((after - before))
+	assertTrue 'Immediate-quit timeout' '[ $delay -ge $READ_X_TIMEOUT ]'
 
-  mainTestTearDown
-  unset READ_X_TIMEOUT
+	mainTestTearDown
+	unset READ_X_TIMEOUT
 }
 
 . ../utility/shunit2
diff --git a/freenx-redesign/server/utility/nxloadconfig b/freenx-redesign/server/utility/nxloadconfig
--- a/freenx-redesign/server/utility/nxloadconfig
+++ b/freenx-redesign/server/utility/nxloadconfig
@@ -55,7 +55,6 @@ PATH_BASE="${PATH_BASE:-/usr/freenx}"
 PATH_ETC="${PATH_ETC:-$PATH_BASE/etc}"
 PATH_BIN="${PATH_BIN:-$PATH_BASE/bin}"
 
-
 check_command_vars() {
 	check_command_var COMMAND_START_KDE "$(which startkde:-NOTFOUND)"
 	check_command_var COMMAND_START_GNOME "$(which gnome-session:-NOTFOUND)"
@@ -72,7 +71,6 @@ check_command_vars() {
 	check_command_var NXSESSION_HOOK "$(which nxsession:-NOTFOUND)"
 }
 
-
 check_dir_vars() {
 	check_dir_var PATH_BASE "$PATH_BASE"
 	check_dir_var PATH_BIN "$PATH_BASE/bin"
@@ -80,11 +78,10 @@ check_dir_vars() {
 	check_dir_var PATH_LIB "$PATH_BASE/lib"
 }
 
-
 parse_args() {
 	# Horrible hack to parse the output of getopt correctly
 	eval ARGS=("$("$COMMAND_GETOPT" -n "$SCRIPT_NAME" -o "h" -l "config:,help" -- \
-	"${ORIG_ARGS[@]:-}")")
+		"${ORIG_ARGS[@]:-}")")
 
 	if [ "$?" != "0" ]; then
 		echo "Error: unable to parse arguments: \"${ORIG_ARGS[@]}\"" >&2
@@ -92,22 +89,32 @@ parse_args() {
 	fi
 }
 
-
 process_args() {
 	local HELP="no"
 
 	while true; do
 		case "$1" in
-			--config) CONF_NAME="$2"; shift 2 ;;
-			-h|--help) HELP="yes"; shift ;;
-			--) shift; break ;;
-			*) echo "$SCRIPT_NAME: error parsing cmdline: $@" >&2; exit 1 ;;
+			--config)
+				CONF_NAME="$2"
+				shift 2
+				;;
+			-h | --help)
+				HELP="yes"
+				shift
+				;;
+			--)
+				shift
+				break
+				;;
+			*)
+				echo "$SCRIPT_NAME: error parsing cmdline: $@" >&2
+				exit 1
+				;;
 		esac
 	done
 
 	[ "$HELP" = "yes" ] && usage
 }
-
 
 usage() {
 	{
@@ -121,14 +128,12 @@ usage() {
 	exit 0
 }
 
-
 default_if_not_set() {
 	local var="$1"
 	local default="$2"
 
 	# Is the var set?
-	if ! declare -p "$var" &> /dev/null
-	then
+	if ! declare -p "$var" &>/dev/null; then
 		# Var is not set, set it to the default now and return
 		eval "$var"="\"$default\""
 		return 0
@@ -138,7 +143,6 @@ default_if_not_set() {
 	fi
 }
 
-
 check_dir_var() {
 	local var="$1"
 	local defdir="$2"
@@ -147,8 +151,7 @@ check_dir_var() {
 
 	# Only check current value if it's actually been set
 	if ! default_if_not_set "$var" "$defdir"; then
-		if [ ! -d "$varval" ]
-		then
+		if [ ! -d "$varval" ]; then
 			nxlog_log $_NXLOG_LOG_WARNING "Invalid directory variable $var: \"$varval\""
 			eval "$var"="\"$defdir\""
 		else
@@ -157,13 +160,11 @@ check_dir_var() {
 		fi
 	fi
 
-	if [ ! -d "$defdir" ]
-	then
+	if [ ! -d "$defdir" ]; then
 		nxlog_log $_NXLOG_LOG_ERR "Invalid default directory variable $var: \"$defdir\""
 		exit 1
 	fi
 }
-
 
 check_command_var() {
 	local var="$1"
@@ -173,8 +174,7 @@ check_command_var() {
 
 	# Only check current value if it's actually been set
 	if ! default_if_not_set "$var" "$defcmd"; then
-		if [ ! -x "$varval" -o ! -f "$varval" ]
-		then
+		if [ ! -x "$varval" -o ! -f "$varval" ]; then
 			nxlog_log $_NXLOG_LOG_WARNING "Invalid command variable $var: \"$varval\""
 			eval "$var"="\"$defcmd\""
 		else
@@ -187,14 +187,12 @@ check_command_var() {
 	if [ "$defcmd" = "" ]; then
 		eval "$var"="\"NOTFOUND\""
 	else
-		if [ ! -x "$defcmd" -o ! -f "$defcmd" ]
-		then
+		if [ ! -x "$defcmd" -o ! -f "$defcmd" ]; then
 			nxlog_log $_NXLOG_LOG_ERR "Invalid default command variable $var: \"$defcmd\""
 			exit 1
 		fi
 	fi
 }
-
 
 load_file() {
 	local file="$1"
@@ -220,8 +218,8 @@ nxloadconfig_main() {
 	load_file "nxlog"
 
 	# Load function-specific configuration
-	[ -n "${CONF_NAME:-}" -a -e "$PATH_ETC/${CONF_NAME:-}.conf" ] && \
-		load_file "$PATH_ETC/$CONF_NAME.conf"
+	[ -n "${CONF_NAME:-}" -a -e "$PATH_ETC/${CONF_NAME:-}.conf" ] \
+		&& load_file "$PATH_ETC/$CONF_NAME.conf"
 
 	# In case the function-specific config updates $LOG_LEVEL
 	_nxlog_set_log_level
diff --git a/freenx-server/nxsetup b/freenx-server/nxsetup
--- a/freenx-server/nxsetup
+++ b/freenx-server/nxsetup
@@ -25,37 +25,84 @@ BUILD_KNOWN_HOSTS="yes"
 AUTOMATIC="no"
 IGNORE_ERRORS="no"
 
-if [ $UID -ne 0 ]
-then
-	echo "You need to be root to use this program." 
+if [ $UID -ne 0 ]; then
+	echo "You need to be root to use this program."
 	exit 1
 fi
 
-parse_cmdline()
-{
-	while [ "$1" ]
-	do
+parse_cmdline() {
+	while [ "$1" ]; do
 		case "$1" in
-			--help) HELP="yes"; shift ;;
-			--install) INSTALL="yes"; shift ;;
-			--ignore-errors) IGNORE_ERRORS="yes"; shift;;
-			--setup-nomachine-key) SETUP_NOMACHINE_KEY="yes"; shift ;;
-			--ssh2) SETUP_SSH2_KEY="yes"; shift;;
-			--dont-build-known-hosts) BUILD_KNOWN_HOSTS="no"; shift;;
-			--uid) SETUP_UID=$2; shift 2 ;;
-			--gid) SETUP_GID=$2; shift 2 ;;
-			--localuser) SETUP_LOCAL_USER="yes"; shift;;
-			--clean) CLEAN="yes"; shift ;;
-			--uninstall) UNINSTALL="yes"; shift ;;
-			--purge) PURGE="yes"; shift ;;
-			--auto) AUTOMATIC="yes"; shift ;;
-			--test) TEST="yes"; shift ;;
-			--) shift ; break ;;
-			*) echo "Invalid flag $1" ; HELP="yes"; shift ; break ;;
+			--help)
+				HELP="yes"
+				shift
+				;;
+			--install)
+				INSTALL="yes"
+				shift
+				;;
+			--ignore-errors)
+				IGNORE_ERRORS="yes"
+				shift
+				;;
+			--setup-nomachine-key)
+				SETUP_NOMACHINE_KEY="yes"
+				shift
+				;;
+			--ssh2)
+				SETUP_SSH2_KEY="yes"
+				shift
+				;;
+			--dont-build-known-hosts)
+				BUILD_KNOWN_HOSTS="no"
+				shift
+				;;
+			--uid)
+				SETUP_UID=$2
+				shift 2
+				;;
+			--gid)
+				SETUP_GID=$2
+				shift 2
+				;;
+			--localuser)
+				SETUP_LOCAL_USER="yes"
+				shift
+				;;
+			--clean)
+				CLEAN="yes"
+				shift
+				;;
+			--uninstall)
+				UNINSTALL="yes"
+				shift
+				;;
+			--purge)
+				PURGE="yes"
+				shift
+				;;
+			--auto)
+				AUTOMATIC="yes"
+				shift
+				;;
+			--test)
+				TEST="yes"
+				shift
+				;;
+			--)
+				shift
+				break
+				;;
+			*)
+				echo "Invalid flag $1"
+				HELP="yes"
+				shift
+				break
+				;;
 		esac
 	done
 
-	[ "$TEST" = "yes" ] && return         # If we just test, we can return directly
+	[ "$TEST" = "yes" ] && return # If we just test, we can return directly
 
 	#Check for invalid combinations:
 	[ "$SETUP_LOCAL_USER" = "yes" -a -z "$LOCAL_USER_OPTION" ] && HELP="yes"
@@ -65,8 +112,7 @@ parse_cmdline()
 	[ "$UNINSTALL" = "yes" -a "$CLEAN" = "yes" ] && HELP="yes"
 	[ "$SETUP_SSH2_KEY" = "yes" -a "$SETUP_NOMACHINE_KEY" = "no" ] && HELP="yes"
 
-	if [ "$INSTALL" = "no" -a "$UNINSTALL" = "no" -a "$AUTOMATIC" = "no" -a "$HELP" = "no" ]
-	then
+	if [ "$INSTALL" = "no" -a "$UNINSTALL" = "no" -a "$AUTOMATIC" = "no" -a "$HELP" = "no" ]; then
 		echo "------> You did select no action."
 		echo "        FreeNX guesses that you want to _install_ the server."
 		echo "        Type \"y\" to abort the installation at this point in time."
@@ -81,8 +127,7 @@ parse_cmdline()
 
 	[ "$INSTALL" = "no" -a "$UNINSTALL" = "no" ] && HELP="yes"
 
-	if [ "$HELP" = "yes" ]
-	then
+	if [ "$HELP" = "yes" ]; then
 		echo "nxsetup - Setup the FreeNX server."
 		echo "Syntax: nxsetup --help"
 		echo "        nxsetup --test [--ignore-errors]"
@@ -103,8 +148,8 @@ parse_cmdline()
 		echo "                         own _commercial_ ssh2-key is not supported!"
 		echo "  --uid <number>         Give the uid <number> to the user \"nx\"."
 		echo "  --gid <number>         Give the gid <number> to the user \"nx\"."
-		[ -n "$LOCAL_USER_OPTION" ] && \
-		echo "  --localuser            The special user \"nx\" will be created locally using"
+		[ -n "$LOCAL_USER_OPTION" ] \
+			&& echo "  --localuser            The special user \"nx\" will be created locally using"
 		echo "                         \"luseradd\", for use in NIS and NISplus environments."
 		echo "  --clean                Perform an uninstallation prior to installation."
 		echo "  --uninstall            Remove log and session files, as well as the special"
@@ -121,8 +166,7 @@ parse_cmdline()
 	#					expect should handle nx-users known-hosts keys so why borther
 	#					in nxsetup?
 
-	if [ "$INSTALL" = "yes" -a "$AUTOMATIC" = "no" -a "$SETUP_NOMACHINE_KEY" = "no" ]
-	then
+	if [ "$INSTALL" = "yes" -a "$AUTOMATIC" = "no" -a "$SETUP_NOMACHINE_KEY" = "no" ]; then
 		echo "------> It is recommended that you use the NoMachine key for"
 		echo "        easier setup. If you answer \"y\", FreeNX creates a custom"
 		echo "        KeyPair and expects you to setup your clients manually. "
@@ -139,44 +183,36 @@ parse_cmdline "$@"
 # Read the config file
 . $(PATH=$(cd $(dirname $0) && pwd):$PATH which nxloadconfig) --
 
-run_nscd()
-{
-	if [ -f /var/run/nscd/nscd.pid ]
-	then
+run_nscd() {
+	if [ -f /var/run/nscd/nscd.pid ]; then
 		nscd "$@" 2>/dev/null || true
 	fi
 }
 
-nx_user_exists()
-{
-	if [ "$SETUP_LOCAL_USER" = "yes" ]
-	then
+nx_user_exists() {
+	if [ "$SETUP_LOCAL_USER" = "yes" ]; then
 		egrep "^nx:" /etc/passwd >/dev/null
 	else
 		getent passwd nx >/dev/null
 	fi
-}	
-nx_group_exists()
-{
+}
+nx_group_exists() {
 	# useradd/adduser need a valid group to add the user to
-	if [ "$SETUP_LOCAL_USER" = "yes" ]
-	then
+	if [ "$SETUP_LOCAL_USER" = "yes" ]; then
 		egrep "^nx:" /etc/group >/dev/null
 	else
 		getent group nx >/dev/null
 	fi
-}	
+}
 
 # Tries to add a system user
-useradd_nx()
-{
+useradd_nx() {
 	# In any case create the basedir of the HOME directory before, 
 	# because useradd will fail to make more than one directory
 	mkdir -p $(dirname "$NX_HOME_DIR")
 
 	# Is it a debian?
-	if [ -f /etc/debian_version -a -z "$SETUP_UID" ]
-	then
+	if [ -f /etc/debian_version -a -z "$SETUP_UID" ]; then
 		USERADD_OPTIONS="--ingroup nx --system --home $NX_HOME_DIR --shell $PATH_BIN/nxserver"
 		[ -n "$SETUP_GID" ] && GROUPADD_OPTIONS="--gid $SETUP_GID"
 
@@ -186,26 +222,23 @@ useradd_nx()
 
 		adduser $USERADD_OPTIONS nx
 		[ -f /etc/nscd.conf ] && { run_nscd --invalidate passwd; }
-		
-	# no, its a "normal" useradd
+
+		# no, its a "normal" useradd
 	else
 		USERADD_OPTIONS="-g nx -d $NX_HOME_DIR -s $PATH_BIN/nxserver"
 		[ -n "$SETUP_GID" ] && GROUPADD_OPTIONS="-g $SETUP_GID"
 
 		# uid specified?
-		if [ -n "$SETUP_UID" ]
-		then
+		if [ -n "$SETUP_UID" ]; then
 			USERADD_OPTIONS="-u $SETUP_UID $USERADD_OPTIONS"
-		
-		# Is it a SuSE?
-		elif [ -f /etc/SuSE-release ]
-		then
+
+			# Is it a SuSE?
+		elif [ -f /etc/SuSE-release ]; then
 			USERADD_OPTIONS="-r $USERADD_OPTIONS"
 		fi
-		
-		if [ "$SETUP_LOCAL_USER" = "yes" ]
-		then
-			! nx_group_exists && lgroupadd $GROUPADD_OPTIONS nx 
+
+		if [ "$SETUP_LOCAL_USER" = "yes" ]; then
+			! nx_group_exists && lgroupadd $GROUPADD_OPTIONS nx
 			[ -f /etc/nscd.conf ] && { run_nscd --invalidate group; }
 
 			luseradd $USERADD_OPTIONS nx
@@ -218,19 +251,16 @@ useradd_nx()
 			[ -f /etc/nscd.conf ] && { run_nscd --invalidate passwd; }
 		fi
 
-		
 	fi
 
 	# the nx user account might be locked, so unlock it.
 	passwd -u nx
 }
 
-install_nx()
-{
+install_nx() {
 	set -e
-	
-	if [ "$(pidof sshd 2>/dev/null)" = "" ]
-	then 
+
+	if [ "$(pidof sshd 2>/dev/null)" = "" ]; then
 		echo -n "Starting ssh service ..."
 		# Generate Host keys if they are not available, yet
 		[ -e /etc/ssh/ssh_host_rsa_key ] || $COMMAND_SSH_KEYGEN -q -t rsa -f /etc/ssh/ssh_host_rsa_key -C '' -N ''
@@ -239,67 +269,61 @@ install_nx()
 		[ -x /etc/init.d/ssh ] && /etc/init.d/ssh start
 		echo "done"
 	fi
-	
+
 	echo -n "Setting up $NX_ETC_DIR ..."
 	mkdir -p $NX_ETC_DIR
 	touch $NX_ETC_DIR/passwords $NX_ETC_DIR/passwords.orig
 	chmod 600 $NX_ETC_DIR/passwords $NX_ETC_DIR/passwords.orig
 	echo "done"
-	
-	if [ ! -f $NX_ETC_DIR/users.id_dsa ]
-	then
+
+	if [ ! -f $NX_ETC_DIR/users.id_dsa ]; then
 		$COMMAND_SSH_KEYGEN -f $NX_ETC_DIR/users.id_dsa -t dsa -N ""
 	fi
-	
+
 	echo -n "Setting up $NX_SESS_DIR ..."
 	mkdir -p $NX_SESS_DIR/closed $NX_SESS_DIR/running $NX_SESS_DIR/failed
 	chmod 700 $NX_SESS_DIR/*
 	echo "done"
-	
+
 	echo -n "Setting up $NX_LOGFILE ..."
 	mkdir -p $(dirname "$NX_LOGFILE")
 	touch "$NX_LOGFILE"
 	chmod 600 "$NX_LOGFILE"
 	echo "done"
-	
-	if ! nx_user_exists
-	then
+
+	if ! nx_user_exists; then
 		echo -n "Setting up special user \"nx\" ..."
 		useradd_nx
 		echo "done"
 	fi
-	
-	if [ "$ENABLE_USESSION" = "1" ]
-	then
+
+	if [ "$ENABLE_USESSION" = "1" ]; then
 		echo -n "Adding user \"nx\" to group \"utmp\" ..."
 		usermod -G utmp nx
 		echo "done"
 	fi
-	
-	if [ "$ENABLE_NOMACHINE_FORWARD_PORT" = "1" -a -x "$NOMACHINE_SERVER" ]
-	then
+
+	if [ "$ENABLE_NOMACHINE_FORWARD_PORT" = "1" -a -x "$NOMACHINE_SERVER" ]; then
 		echo -n "Setting up NoMachine forwarding ..."
 		usermod -s "$PATH_BIN/nxserver" -d "$NOMACHINE_NX_HOME_DIR" nx
 		echo "done"
 	fi
-	
+
 	echo -n "Setting up known_hosts and $SSH_AUTHORIZED_KEYS ..."
-	
+
 	SETUP_NX_KEY="no"
-	
+
 	mkdir -p $NX_HOME_DIR/.ssh
 	chmod 700 $NX_HOME_DIR/ $NX_HOME_DIR/.ssh
-	
-	if [ ! -f $NX_HOME_DIR/.ssh/$SSH_AUTHORIZED_KEYS -o "$SETUP_NOMACHINE_KEY" = "yes" ]
-	then
+
+	if [ ! -f $NX_HOME_DIR/.ssh/$SSH_AUTHORIZED_KEYS -o "$SETUP_NOMACHINE_KEY" = "yes" ]; then
 		SETUP_NX_KEY="yes"
-		if [ "$SETUP_NOMACHINE_KEY" = "yes" ]
-		then
-			cat << EOF >$NX_HOME_DIR/.ssh/$SSH_AUTHORIZED_KEYS
+		if [ "$SETUP_NOMACHINE_KEY" = "yes" ]; then
+			cat <<EOF >$NX_HOME_DIR/.ssh/$SSH_AUTHORIZED_KEYS
 no-port-forwarding,no-agent-forwarding,command="$PATH_BIN/nxserver" ssh-dss AAAAB3NzaC1kc3MAAACBAJe/0DNBePG9dYLWq7cJ0SqyRf1iiZN/IbzrmBvgPTZnBa5FT/0Lcj39sRYt1paAlhchwUmwwIiSZaON5JnJOZ6jKkjWIuJ9MdTGfdvtY1aLwDMpxUVoGwEaKWOyin02IPWYSkDQb6cceuG9NfPulS9iuytdx0zIzqvGqfvudtufAAAAFQCwosRXR2QA8OSgFWSO6+kGrRJKiwAAAIEAjgvVNAYWSrnFD+cghyJbyx60AAjKtxZ0r/Pn9k94Qt2rvQoMnGgt/zU0v/y4hzg+g3JNEmO1PdHh/wDPVOxlZ6Hb5F4IQnENaAZ9uTZiFGqhBO1c8Wwjiq/MFZy3jZaidarLJvVs8EeT4mZcWxwm7nIVD4lRU2wQ2lj4aTPcepMAAACANlgcCuA4wrC+3Cic9CFkqiwO/Rn1vk8dvGuEQqFJ6f6LVfPfRTfaQU7TGVLk2CzY4dasrwxJ1f6FsT8DHTNGnxELPKRuLstGrFY/PR7KeafeFZDf+fJ3mbX5nxrld3wi5titTnX+8s4IKv29HJguPvOK/SI7cjzA+SqNfD7qEo8= root@nettuno
 EOF
 			chmod 600 $NX_HOME_DIR/.ssh/$SSH_AUTHORIZED_KEYS
-			cat << EOF >$NX_HOME_DIR/.ssh/client.id_dsa.key
+			cat <<EOF >$NX_HOME_DIR/.ssh/client.id_dsa.key
 -----BEGIN DSA PRIVATE KEY-----
 MIIBuwIBAAKBgQCXv9AzQXjxvXWC1qu3CdEqskX9YomTfyG865gb4D02ZwWuRU/9
 C3I9/bEWLdaWgJYXIcFJsMCIkmWjjeSZyTmeoypI1iLifTHUxn3b7WNWi8AzKcVF
@@ -326,12 +350,11 @@ EOF
 	SSH2_AUTHORIZATION="authorization"
 	SSH2_PUBKEY="nx_user.id.pub"
 	SSH2_HOME_DIR="$NX_HOME_DIR/.ssh2"
-	if [ ! -f "${SSH2_HOME_DIR}/$SSH2_PUBKEY" -a "$SETUP_SSH2_KEY" = "yes" -a "$SETUP_NOMACHINE_KEY" = "yes" ]
-	then
+	if [ ! -f "${SSH2_HOME_DIR}/$SSH2_PUBKEY" -a "$SETUP_SSH2_KEY" = "yes" -a "$SETUP_NOMACHINE_KEY" = "yes" ]; then
 		mkdir -p $SSH2_HOME_DIR
 		chmod 700 $SSH2_HOME_DIR
-		
-		cat >  ${SSH2_HOME_DIR}/$SSH2_PUBKEY <<EOF
+
+		cat >${SSH2_HOME_DIR}/$SSH2_PUBKEY <<EOF
 ---- BEGIN SSH2 PUBLIC KEY ----
 Comment: "1024-bit DSA, converted from OpenSSH by root@localhost"
 AAAAB3NzaC1kc3MAAACBAJe/0DNBePG9dYLWq7cJ0SqyRf1iiZN/IbzrmBvgPTZnBa5FT/
@@ -345,19 +368,18 @@ NGnxELPKRuLstGrFY/PR7KeafeFZDf+fJ3mbX5nxrld3wi5titTnX+8s4IKv29HJguPvOK
 /SI7cjzA+SqNfD7qEo8=
 ---- END SSH2 PUBLIC KEY ----
 EOF
-		echo "Key $SSH2_PUBKEY" >> ${SSH2_HOME_DIR}/$SSH2_AUTHORIZATION
-		echo "Options no-port-forwarding,no-agent-forwarding,command=\"$PATH_BIN/nxserver\"" >> ${SSH2_HOME_DIR}/$SSH2_AUTHORIZATION
+		echo "Key $SSH2_PUBKEY" >>${SSH2_HOME_DIR}/$SSH2_AUTHORIZATION
+		echo "Options no-port-forwarding,no-agent-forwarding,command=\"$PATH_BIN/nxserver\"" >>${SSH2_HOME_DIR}/$SSH2_AUTHORIZATION
 		chmod 600 ${SSH2_HOME_DIR}/$SSH2_AUTHORIZATION ${SSH2_HOME_DIR}/$SSH2_PUBKEY
 	fi
-	
-	if [ ! -f $NX_HOME_DIR/.ssh/known_hosts -a "$BUILD_KNOWN_HOSTS" = "yes" ]
-	then
-		echo -n "127.0.0.1 " > $NX_HOME_DIR/.ssh/known_hosts
-		cat /etc/ssh/ssh_host_rsa_key.pub >> $NX_HOME_DIR/.ssh/known_hosts
+
+	if [ ! -f $NX_HOME_DIR/.ssh/known_hosts -a "$BUILD_KNOWN_HOSTS" = "yes" ]; then
+		echo -n "127.0.0.1 " >$NX_HOME_DIR/.ssh/known_hosts
+		cat /etc/ssh/ssh_host_rsa_key.pub >>$NX_HOME_DIR/.ssh/known_hosts
 	fi
-	
+
 	echo "done"
-	
+
 	echo -n "Setting up permissions ..."
 	chown -R nx:root $NX_SESS_DIR
 	chown -R nx:root $NX_ETC_DIR
@@ -366,8 +388,7 @@ EOF
 
 	echo "done"
 
-	if [ -d "$CUPS_BACKEND" ]
-	then
+	if [ -d "$CUPS_BACKEND" ]; then
 		echo -n "Setting up cups nxipp backend ..."
 		cp -af "$CUPS_BACKEND/ipp" "$CUPS_IPP_BACKEND"
 		chmod 755 "$CUPS_IPP_BACKEND"
@@ -375,8 +396,7 @@ EOF
 	fi
 }
 
-test_nx()
-{
+test_nx() {
 	echo ""
 	echo "----> Testing your nxserver configuration ..."
 	[ "$IGNORE_ERRORS" = "yes" ] && NO_ERRORS="--ignore-errors"
@@ -384,31 +404,29 @@ test_nx()
 	echo "<---- done"
 	echo ""
 	echo "----> Testing your nxserver connection ..."
-	
+
 	CONNECTION=""
-	while read -t 3 line
-	do
+	while read -t 3 line; do
 		echo $line
-		
+
 		case "$line" in
 			*"HELLO NXSERVER - Version $NX_VERSION"*)
 				CONNECTION="yes"
-			;;
+				;;
 			*"HELLO NXSERVER - Version"*)
 				echo "Warning: Version mismatch. Expected $NX_VERSION got: $line."
 				CONNECTION="yes"
-			;;
+				;;
 			*"NX> 999 Bye"*)
-				break;
-			;;
+				break
+				;;
 		esac
 
 	done < <(NODE_PUBLICKEY="$NX_HOME_DIR/.ssh/client.id_dsa.key" $PATH_BIN/nxnode-login test-nx nx "$SSHD_PORT" nxserver --check)
 
-	if [ -z "$CONNECTION" ]
-	then
+	if [ -z "$CONNECTION" ]; then
 		echo "Fatal error: Could not connect to NX Server."
-		echo 
+		echo
 		echo "Please check your ssh setup:"
 		echo ""
 		echo "The following are _examples_ of what you might need to check."
@@ -433,81 +451,72 @@ test_nx()
 	echo ""
 }
 
-uninstall_nx() 
-{
-	if nx_user_exists
-	then
+uninstall_nx() {
+	if nx_user_exists; then
 		echo -n "Removing special user \"nx\" ..."
-		
-		if [ "$SETUP_LOCAL_USER" = "yes" ]
-		then
+
+		if [ "$SETUP_LOCAL_USER" = "yes" ]; then
 			luserdel nx
 		else
 			userdel nx
 		fi
-			
+
 		echo "done"
 	fi
-	
-	if [ -e "$NX_SESS_DIR" ]
-	then
+
+	if [ -e "$NX_SESS_DIR" ]; then
 		echo -n "Removing session database ..."
 		rm -f -r $NX_SESS_DIR/closed $NX_SESS_DIR/running $NX_SESS_DIR/failed 2>/dev/null
 		rmdir -p $NX_SESS_DIR 2>/dev/null
 		echo "done"
 	fi
-	
-	if [ -e "$NX_LOGFILE" ] 
-	then
+
+	if [ -e "$NX_LOGFILE" ]; then
 		echo -n "Removing logfile ..."
 		rm -f "$NX_LOGFILE" 2>/dev/null
 		rmdir -p $(dirname "$NX_LOGFILE") 2>/dev/null
 		echo "done"
 	fi
-	
-	if [ "$PURGE" = "yes" -a -e "$NX_HOME_DIR" ]
-	then
+
+	if [ "$PURGE" = "yes" -a -e "$NX_HOME_DIR" ]; then
 		echo -n "Removing home directory of special user \"nx\" ..."
 		rm -f -r "$NX_HOME_DIR" 2>/dev/null
 		rmdir -p $(dirname "$NX_HOME_DIR") 2>/dev/null
 		echo "done"
 	fi
-	
-	if [ "$PURGE" = "yes" -a -e "$NX_ETC_DIR" ]
-	then
+
+	if [ "$PURGE" = "yes" -a -e "$NX_ETC_DIR" ]; then
 		echo -n "Removing configuration files ..."
 		rm -f "$NX_ETC_DIR/passwords" "$NX_ETC_DIR/passwords.orig" "$NX_ETC_DIR/users.id_dsa" "$NX_ETC_DIR/users.id_dsa.pub" 2>/dev/null
-		for i in `ls $NX_ETC_DIR/*.node.conf 2>/dev/null` ;
-		do
-			rm -f "$i" 2>/dev/null;
+		for i in $(ls $NX_ETC_DIR/*.node.conf 2>/dev/null); do
+			rm -f "$i" 2>/dev/null
 		done
 		echo "done"
 	fi
 }
 
-if [ "$TEST" = "yes" ]
-then
+if [ "$TEST" = "yes" ]; then
 	test_nx
 	exit 0
 fi
 
-if [ "$INSTALL" = "yes" ]
-then
+if [ "$INSTALL" = "yes" ]; then
 	#Perform cleanup?
 	[ "$CLEAN" = "yes" ] && uninstall_nx
-	
-	[ -f /etc/nscd.conf ] && { run_nscd --invalidate passwd; run_nscd --invalidate group; }
+
+	[ -f /etc/nscd.conf ] && {
+		run_nscd --invalidate passwd
+		run_nscd --invalidate group
+	}
 	install_nx
 
 	[ "$AUTOMATIC" = "no" ] && test_nx
-	
+
 	echo "Ok, nxserver is ready."
-	echo 
-	if [ "$ENABLE_SSH_AUTHENTICATION" = "1" -o "$ENABLE_SU_AUTHENTICATION" = "1" ]
-	then
+	echo
+	if [ "$ENABLE_SSH_AUTHENTICATION" = "1" -o "$ENABLE_SU_AUTHENTICATION" = "1" ]; then
 		echo "PAM authentication enabled:"
-		if [ "$ENABLE_USER_DB" = "1" ]
-		then
+		if [ "$ENABLE_USER_DB" = "1" ]; then
 			echo "  Users will be able to login with their normal passwords,"
 			echo "  but they have to be registered in the NX database to do so."
 			echo "  To add new users to the NX user database do:"
@@ -516,13 +525,11 @@ then
 			echo "  All users will be able to login with their normal passwords."
 		fi
 		echo
-		if [ "$ENABLE_SSH_AUTHENTICATION" = "1" -a "$ENABLE_SU_AUTHENTICATION" = "1" ]
-		then
+		if [ "$ENABLE_SSH_AUTHENTICATION" = "1" -a "$ENABLE_SU_AUTHENTICATION" = "1" ]; then
 			echo "  Both SSH and SU authentication is enabled."
 			echo "  This does work, but is redundant."
 			echo "  Please check if this is really what you intended."
-		elif [ "$ENABLE_SSH_AUTHENTICATION" = "1" ]
-		then
+		elif [ "$ENABLE_SSH_AUTHENTICATION" = "1" ]; then
 			echo "  PAM authentication will be done through SSH."
 			echo "  Please ensure that SSHD on localhost accepts password authentication."
 		else
@@ -540,9 +547,8 @@ then
 	fi
 	echo
 	echo "  You can change this behaviour in the $NX_ETC_DIR/node.conf file."
-	
-	if [ "$SETUP_NOMACHINE_KEY" = "no" -a "$SETUP_NX_KEY" = "yes" ]
-	then
+
+	if [ "$SETUP_NOMACHINE_KEY" = "no" -a "$SETUP_NX_KEY" = "yes" ]; then
 		echo
 		echo "Warning: Clients will not be able to login to this server with the standard key."
 		echo "         Please replace /usr/NX/share/client.id_dsa.key on all clients you want"
@@ -555,16 +561,14 @@ then
 		echo "         '$NX_HOME_DIR/.ssh/$SSH_AUTHORIZED_KEYS'"
 		echo "         and then run this script with the --setup-nomachine-key parameter."
 	fi
-	
+
 	echo "Have Fun!"
-elif [ "$UNINSTALL" = "yes" ]
-then
+elif [ "$UNINSTALL" = "yes" ]; then
 	uninstall_nx
-	
+
 	echo "Ok, nxserver is uninstalled"
-	echo 
-	if [ "$PURGE" = "yes" ]
-	then
+	echo
+	if [ "$PURGE" = "yes" ]; then
 		echo "To complete the uninstallation process, remove the FreeNX scripts in $PATH_BIN"
 		echo "and the $NX_ETC_DIR/node.conf configuration file."
 	else
